# .travis.yml
language: node_js
node_js:
    - "10"
services:
  - mysql
# 設定參數(Travis CI 會按照參數分別執行)
env:
  - NODE_ENV=test
# 在 install 前執行的指令
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS recus_platform_test default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - export JWT_SECRET=alphacamp
# 在執行測試之前的指令
before_script:
  - cd server
  - sequelize db:migrate

script:
  - npm test

# deploy:
#   provider: heroku
#   api_key:
#     secure: 4e9c83a0-10fd-48ed-b932-d4761e69e76e
#   app: recusplatform
#   on:
#     repo: IgnacioFan/recus-platform

#     // deploy設定是要交給master還是develop呢